### ISSUE TITLE
Support for aliasing units against already defined units for that quantity

### ISSUE THREAD

**Issue by triplepoint** [UnitsOfMeasure/units-of-measure-definitions#4]
This will require a high-level language version bump.

Right now, the quantity definition for `Mass` looks like:

``` yaml
- name: Mass
    si_unit:
      names: [kg, kilogram, kilograms]
      metric_prefixes:
        patterns: [%{p}g, %{P}gram, %{P}grams]
        base_metric_unit_scaling_factor: 1e-3
    additional_units:
      - 1e3 = t, ton, tons
      - 4.5359237e-1 = lb, lbs, pound, pounds
      - 4.5359237e-1 / 16 = oz, ounce, ounces
      - 4.5359237e-1 * 14 = st, stone, stones
```

It'd be great to be able to do something like this:

``` yaml
- name: Mass
    si_unit:
      names: [kg, kilogram, kilograms]
      metric_prefixes:
        patterns: [%{p}g, %{P}gram, %{P}grams]
        base_metric_unit_scaling_factor: 1e-3
    additional_units:
      - 1e3 kg = t, ton, tons
      - 4.5359237e-1 kg = lb, lbs, pound, pounds 
      - 1/16 lb = oz, ounce, ounces
      - 14 lbs = st, stone, stones
```
